### ISSUE TITLE
Please describe this project properly

### ISSUE THREAD

**Issue by DrJohnT** [jadson179/controlid#7]
This came up on my HA instance as a new repo.  Having looked at your repo, I still have no idea what it does.  Please explain for myself and others.

**Comment by gtjadsonsantos** [comment]
Hi my friend, i do will  updated README.md with a best describre.

**Comment by gtjadsonsantos** [comment]
# CONTROL ID

This custom integration permits Home Assistant to communicate with `controlid` controllers through  http requests.

**Whats does it do?**
- Allow opening the doors/access points

**Tested hardwares**:
- idFlex: https://www.controlid.com.br/docs/idbox-pt/
- idBox: https://www.controlid.com.br/docs/idbox-pt/

**Comment by gtjadsonsantos** [comment]
Thanks friend.
